name: flutter_refresh_loadmore
description: A refresh loadmore listview package. can pull refresh listview and loadmore ,use  the libray listview  swrap  form the new widget.
version: 0.2.0
#author: liu wangle<liuwangle1789@gmail.com>
homepage: https://github.com/liuwangle/flutter_refresh_loadmore


environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

